### ISSUE TITLE
Initialize Project

### ISSUE THREAD

**Issue by GuillaumeWaignier** [Zenika/kafka-monitoring#1]
## TODO

- [x] Docker compose with 3 kafka, 3 zookeeper, 2 schema-registry, 2 kconnect with security SASL_PLAINTEXT
- [ ] Docker compose with grafana, prometheus
- [ ] Add prometheus exporter zookeeper, broker, ...
- [ ] Grafrana dashboard
- [ ] elastic stack ?
- [ ] Kibana custom on security
